/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js and kept in source so strict TypeScript
// works before the first local dev server run.
